### ISSUE TITLE
How should I run this best game ever? I have to play it

### ISSUE THREAD

**Issue by andrewostroumov** [mikhail-efremov/game-jam-2019#1]

**Comment by mikhail-efremov** [comment]
Sure u can! Download rar on https://drive.google.com/drive/u/1/folders/1gC8IxA--aji-ASANwpQ4vo--CfXerQ24
By the way, you need to use Windows to run this beautiful game!
Idealy controlls by PS4 dualshocks, but you can enjoy by use arrows and X, Z to interract with items

**Comment by mikhail-efremov** [comment]
Wait for your feedback!
